# Generated by Django 4.2.5 on 2024-06-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('cal', models.CharField(max_length=50)),
                ('num_exercise', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField(default=True)),
                ('banner', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('add_photo', models.ImageField(upload_to='add_photos/')),
                ('status', models.BooleanField(default=True)),
                ('level', models.CharField(default=None, max_length=500)),
                ('workout_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('time', models.CharField(max_length=50)),
                ('repetition_time', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('recommended', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
    ]
