# Generated by Django 4.2.5 on 2024-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('cal', models.CharField(max_length=50)),
                ('num_exercise', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
