# Generated by Django 4.2.5 on 2024-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
