# Generated by Django 4.2.5 on 2024-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
