# Generated by Django 4.2.5 on 2024-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
