# Generated by Django 4.2.5 on 2024-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workoutbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutbanner',
            name='workout_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
