# Generated by Django 4.2.5 on 2024-06-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_video_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='banner',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
