# Generated by Django 4.2.5 on 2024-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='most_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
