# Generated by Django 4.2.5 on 2024-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_most_popular_alter_product_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='goal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
