# Generated by Django 4.2.5 on 2024-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
