# Generated by Django 4.1.13 on 2024-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('measurement', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ingredient_images/')),
            ],
        ),
    ]
