# Generated by Django 4.1.13 on 2024-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffood',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
