# Generated by Django 4.1.13 on 2024-06-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_dietvideo_timeoffood_id_ingredient_timeoffood_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='carbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diet',
            name='image',
            field=models.ImageField(default=0, upload_to='diet_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='level',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='number_of_intake',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='protein',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diet',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='carbs',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='fat',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='precautions',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='preptime',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='protein',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='video',
            field=models.FileField(default=0, upload_to='diet_videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default=0, upload_to='ingredient_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='calories',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='diet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diet.diet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='image',
            field=models.ImageField(default=0, upload_to='timeoffood_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='number_of_cup',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='number_of_gram',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
