# Generated by Django 4.1.13 on 2024-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_diet_carbs_alter_diet_fat_alter_diet_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dietvideo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeoffood',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
