# Generated by Django 4.1.13 on 2024-06-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_diet_status_alter_dietvideo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietvideo',
            name='timeoffood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.timeoffood', unique=True),
        ),
    ]
