# Generated by Django 4.2.5 on 2024-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_alter_dietvideo_timeoffood_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietvideo',
            name='type',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='dietvideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
