# Generated by Django 4.2.5 on 2024-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default='0'),
        ),
    ]
