# Generated by Django 4.2.5 on 2024-05-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
