# Generated by Django 4.1.13 on 2024-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
