# Generated by Django 4.1.13 on 2024-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoostLifeapp', '0003_alter_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FileField(upload_to='store_images/'),
        ),
    ]
