# Generated by Django 4.1.13 on 2024-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoostLifeapp', '0004_alter_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='newimage',
            field=models.FileField(default=1, upload_to='store_images/'),
            preserve_default=False,
        ),
    ]
