# Generated by Django 4.1.13 on 2024-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoostLifeapp', '0005_remove_store_image_store_newimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
