# Generated by Django 4.1.13 on 2024-08-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='InfluencerLink',
        ),
        migrations.RemoveField(
            model_name='influencerotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Influencer',
        ),
        migrations.DeleteModel(
            name='InfluencerOtp',
        ),
    ]
