# Generated by Django 4.1.13 on 2024-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='commission_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
