# Generated by Django 4.1.13 on 2024-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_influencer_commission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
